# hi_class propto_omega with beyond-Horndeski (6th param = alphaH)
# parameters_smg = c_K, c_B, c_M, c_T, M*2_init, c_H
output = mPk
P_k_max_h/Mpc = 2.5
z_pk = 0
h = 0.6736
omega_b = 0.02237
omega_cdm = 0.12000
tau_reio = 0.0544
n_s = 0.9649
A_s = 2.1e-9
Omega_Lambda = 0.693
Omega_fld = 0
gravity_model = propto_omega
Omega_smg = 0.0
parameters_smg = 1.0, 0.0, 0.0, 0.0, 1.0, 0.020
expansion_smg = wowa
expansion_smg_w0 = -1.0
expansion_smg_wa = 0.0
skip_stability_tests_smg = yes
cs2_safe_smg = -1e30
D_safe_smg = -1e30
